import { getExportMetadata, formatBSDate, formatBSDateTime } from './nepaliCalendar';

export interface CSVColumn<T = any> {
  key: keyof T | string;
  label: string;
  formatter?: (value: any, row: T) => string | number | null | undefined;
}

export interface CSVExportOptions<T = any> {
  filename: string;
  data: T[];
  columns: CSVColumn<T>[];
  reportTitle?: string;
  branchName?: string;
  generatedBy?: string;
  includeMetadataHeader?: boolean;
  /** Official company identity (from Company Profile) embedded in the export metadata header. */
  companyInfo?: { name?: string; legalName?: string; panVatNumber?: string };
}

/**
 * App-wide default company identity used by every exportToCSV call unless a
 * call site passes its own `companyInfo`. The application shell keeps this in
 * sync with the loaded Company Profile via `setExportCompanyProfile`.
 */
let defaultCompanyInfo: CSVExportOptions<any>['companyInfo'];

export function setExportCompanyProfile(
  profile: { name?: string; legalName?: string; panVatNumber?: string } | null | undefined
) {
  defaultCompanyInfo = profile
    ? { name: profile.name, legalName: profile.legalName, panVatNumber: profile.panVatNumber }
    : undefined;
}

/**
 * Enhanced CSV / Excel Data Exporter Utility for Inventory Multi-Branch ERP
 * Includes uniform BS exported date (YYYY-MM-DD HH:mm:ss) and report metadata.
 */
export function exportToCSV<T extends Record<string, any>>(
  filenameOrOptions: string | CSVExportOptions<T>,
  maybeData?: T[],
  maybeColumns?: CSVColumn<T>[],
  maybeCompanyInfo?: CSVExportOptions<T>['companyInfo']
) {
  let filename: string;
  let data: T[];
  let columns: CSVColumn<T>[];
  let reportTitle: string | undefined;
  let branchName: string | undefined;
  let generatedBy: string | undefined;
  let includeMetadataHeader: boolean = true;
  let companyInfo: CSVExportOptions<T>['companyInfo'] | undefined;
  if (typeof filenameOrOptions === 'object' && filenameOrOptions !== null) {
    filename = filenameOrOptions.filename;
    data = filenameOrOptions.data;
    columns = filenameOrOptions.columns;
    reportTitle = filenameOrOptions.reportTitle;
    branchName = filenameOrOptions.branchName;
    generatedBy = filenameOrOptions.generatedBy;
    includeMetadataHeader = filenameOrOptions.includeMetadataHeader ?? true;
    companyInfo = filenameOrOptions.companyInfo ?? maybeCompanyInfo;
  } else {
    filename = typeof filenameOrOptions === 'string' ? filenameOrOptions : 'Report';
    data = maybeData || [];
    columns = maybeColumns || [];
    companyInfo = maybeCompanyInfo;
    reportTitle = filename.replace(/[_-]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  }
  companyInfo = companyInfo || defaultCompanyInfo;

  if (!data || data.length === 0) {
    alert('No data available to export.');
    return;
  }

  const meta = getExportMetadata(reportTitle || filename, branchName, generatedBy);

  const lines: string[] = [];

  // 1. Report Metadata Headers (Includes official BS and AD exported dates)
  if (includeMetadataHeader) {
    lines.push(`"Report:","${(reportTitle || filename).replace(/"/g, '""')}"`);
    lines.push(`"Exported Date (BS):","${meta.exportedDateTimeBS}"`);
    lines.push(`"Exported Date (AD):","${meta.exportedDateTimeAD}"`);
    if (branchName) {
      lines.push(`"Branch / Location:","${branchName.replace(/"/g, '""')}"`);
    }
    if (generatedBy) {
      lines.push(`"Generated By:","${generatedBy.replace(/"/g, '""')}"`);
    }
    const companyName = companyInfo?.legalName || companyInfo?.name;
    if (companyName) {
      lines.push(`"Company:","${companyName.replace(/"/g, '""')}"`);
    }
    if (companyInfo?.panVatNumber) {
      lines.push(`"Company PAN / VAT No:","${companyInfo.panVatNumber.replace(/"/g, '""')}"`);
    }
    lines.push(`"Total Records:","${data.length}"`);
    lines.push(''); // Empty line between metadata and table header
  }

  // 2. Table Column Headers
  const headers = columns.map((col) => `"${col.label.replace(/"/g, '""')}"`).join(',');
  lines.push(headers);

  // 3. Table Data Rows
  data.forEach((row) => {
    const rowContent = columns
      .map((col) => {
        let val = (row as any)[col.key];
        if (col.formatter) {
          val = col.formatter(val, row);
        } else if (val === null || val === undefined) {
          val = '';
        } else if (typeof val === 'object') {
          val = JSON.stringify(val);
        }
        const stringVal = String(val).replace(/"/g, '""');
        return `"${stringVal}"`;
      })
      .join(',');
    lines.push(rowContent);
  });

  const csvContent = '\uFEFF' + lines.join('\n'); // UTF-8 BOM for Excel compatibility

  const cleanFilename = filename.endsWith('.csv') ? filename.replace('.csv', '') : filename;
  const downloadName = `${cleanFilename}_BS_${meta.exportedDateBS}.csv`;

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', downloadName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

